### ISSUE TITLE
Project doesn't compile as is

### ISSUE THREAD

**Issue by AlienAsRoger** [chiuki/friendspell#5]
I've tried all possible different configurations and I still can't get it to work:

I got following error:

Error:Gradle: Execution failed for task ':app:processCannedDebugGoogleServices'.

> File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

I've tried to update:
    classpath 'com.android.tools.build:gradle:2.0.0-alpha9' // from alpha 3
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    classpath 'com.google.gms:google-services:2.0.0-alpha9' // from alpha 3

but still got same error. SO tells that I need to try different version of gms, but in that way I got:

Error:Gradle: Execution failed for task ':app:processCannedDebugGoogleServices'.

> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 8.3.0.

and setting services to 8.3.0 repeat error above. Very frustrating, please help. Thank you!

**Comment by chiuki** [comment]
You need to generate your own `app/google-services.json` file, as explained in the README https://developers.google.com/identity/sign-in/android/start-integrating

**Comment by AlienAsRoger** [comment]
Thank you, and Sorry my stupidity :(
